class FolderConstants {}

// ACTIONS
FolderConstants.ACTION_CREATE_FOLDER = 'ACTION_CREATE_FOLDER';
FolderConstants.ACTION_DELETE_FOLDER = 'ACTION_DELETE_FOLDER';
FolderConstants.ACTION_RENAME_FOLDER = 'ACTION_RENAME_FOLDER';
FolderConstants.ACTION_REORDER_FOLDER = 'ACTION_REORDER_FOLDER';

// EVENTS
FolderConstants.EVENT_FOLDER_DATA_CHANGED = 'EVENT_FOLDER_DATA_CHANGED';

export default FolderConstants;